library(shiny)
library(DT)

# Define UI for CombatSim app ----
ui <- pageWithSidebar(
    
    # App title ----
    headerPanel("D&D 5e Combat Simulator"),
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      tabsetPanel(
        tabPanel(title = "Home", 
                 br(),
                 h4(strong("Welcome to the D&D 5e Combat Simulator!")),
                 br(),
                 p("While still very much a work in progress, in its current state,
                   it's an effective means of simulating rudimentary melee combat between two parties on any scale, from small to large.
                   This simulation uses a suite of custom R functions I have made publicly available on my Github."),
                 br(),
                 p("In order to use this app, please navigate the various tabs in this side panel and adjust the settings 
                   according to your liking. All adjustments will yield changes in the main panel, which will either display 
                   turn-by-turn summaries of the actions of characters or the statistics of the combatants in table format."),
                 br(),
                 p("While this app offers a convenient, accessible, and no-cost means of simulating combat, running the R functions 
                   behind this app locally on your computer offers greater control to shape the battle as you'd like. Additionally, 
                   usage for the online app is capped at 25 hrs (collectively) per month; as such, it may not always be available. 
                   However, if you were to run the app locally on your computer, usage is unlimited."),
                 br(),
                 p("For more information on how to use the simulation most effectively or the planned development timeline, please visit the Github. If you encounter any issues,
                   please feel free to reach out using the links below."), 
                 h3(a('Github', href='https://github.com/Wjpmitchell3/Tabletop-RPG-Tools'), align = 'center'),
                 h3(a('About Me', href='https://sites.google.com/view/wjmitchell/home'), align = 'center'),
                 h3(a('Contact', href='mailto:wjpmitchell3@gmail.com'), align = 'center')),
        tabPanel(title = "CombatSim", 
                 p("Use this panel specify the general details of the battle, like number of groups battling, how long the battle should 
                   run, or even setting a seed to ensure that you can replicate the same simulation in the future."),                 
                 br(),
                 # Input: Number of groups to simulate ----
                 numericInput(inputId = "nGroups", 
                              label = "Groups - How Many Groups Should Battle?:",
                              value = 2,
                              step = 1,
                              min = 2, 
                              width = '75%'),
                 # Input: Number of Sides to simulate ----
                 numericInput(inputId = "nSides", 
                              label = "Sides - How Many Sides Are Battling each other?:",
                              value = input$nGroups,
                              step = 1,
                              min = 2, 
                              width = '75%'),
                 # Input: Checkbox to indicate uniformity in simulated groups ----
                 checkboxInput(inputId = "Uniform",
                               label = "All Members of Each Group Should Have The Same Stats",
                               value = TRUE),
                 # Input: Selector to determine how long simulation should run ----
                 selectInput(inputId = "Ending",
                             label = "How Long Should The Simulation Run:",
                             choices =  c("Until One Side Dies (Deathmatch)" = "Death",
                                          "A Certain Number of Rounds (Timed)" = "Timed"),
                             selected = "Timed",
                             multiple = FALSE, 
                             width = '75%'),
                 # Input: Text entry to determine how many rounds simulation should run, if not death match ----
                 numericInput(inputId = "nRounds",
                              label = "Number of Rounds To Run Simulation (Ignore if using Deathmatch setting):",
                              value = 3,
                              min = 1,
                              step = 1, 
                              width = '75%'),
                 # Input: Selector to determine what turn-by-turn output the users would like ----
                 selectInput(inputId = "PlayByPlay",
                             label =  "Turn-By-Turn Output:",
                             choices = c("All Actions" = "Everything",
                                         "Attacks & Kills Only" = "Attacks",
                                         "Kills Only" = "Kills",
                                         "None" = "Off"),
                             selected = "Off",
                             multiple = FALSE, 
                             width = '75%'),
                 # Input: Text entry to seed simulation ----
                 numericInput(inputId = "Seed", 
                              label = "Seed - An Optional Code To Replicate Simulations:",
                              value = sample(0:999999,1),
                              step = 1,
                              min = 1, 
                              width = '75%')),
        tabPanel(title = "Group 1", 
                 p("Use this panel to specify the details of this party"),                 
                 br(),
                 # Input: Text entry to specify group names ----
                 textInput(inputId = "group1",
                           label = "Name:",
                           value = "Nez's Oblates",
                           placeholder = "Nez's Oblates", 
                           width = '75%'),
                 # Input: Numeric entry to specify group sizes ----                 
                 numericInput(inputId = "nPeople1",
                              label = "Group Size:",
                              min = 1,
                              step = 1,
                              value = 10, 
                              width = '75%'),
                 # Input: Numeric entry to simulate attack bonuses ----
                 numericInput(inputId = "ATK1",
                              label = "ATK Bonus:",
                              min = 0,
                              step = 1,
                              value = 13, 
                              width = '75%'),
                 textInput(inputId = "DMG1",
                           label = "Damage Dice:",
                           placeholder = "3d8 + 8",
                           value = "3d8 + 8", 
                           width = '75%'),
                 numericInput(inputId = "HPmax1",
                              label = "HP max:",
                              min = 1,
                              step = 1,
                              value = 178, 
                              width = '75%'),
                 numericInput(inputId = "STR1",
                              label = "STR:",
                              min = 0,
                              step = 1,
                              value = 20, 
                              width = '75%'),
                 numericInput(inputId = "DEX1",
                              label = "DEX:",
                              min = 0,
                              step = 1,
                              value = 12, 
                              width = '75%')),
        tabPanel(title = "Group 2", 
                 p("Use this panel to specify the details of this party"),                 
                 br(),
                 # Input: Text entry to specify group names ----
                 textInput(inputId = "group2",
                           label = "Name:",
                           value = "the Fiends",
                           placeholder = "Fiends", 
                           width = '75%'),
                 # Input: Numeric entry to specify group sizes ----                 
                 numericInput(inputId = "nPeople2",
                              label = "Group Size:",
                              min = 1,
                              step = 1,
                              value = 150, 
                              width = '75%'),
                 # Input: Numeric entry to simulate attack bonuses ----
                 numericInput(inputId = "ATK2",
                              label = "ATK Bonus:",
                              min = 0,
                              step = 1,
                              value = 4, 
                              width = '75%'),
                 textInput(inputId = "DMG2",
                           label = "Damage Dice:",
                           placeholder = "1d6 + 2",
                           value = "1d6 + 2", 
                           width = '75%'),
                 numericInput(inputId = "HPmax2",
                              label = "HP max:",
                              min = 1,
                              step = 1,
                              value = 30, 
                              width = '75%'),
                 numericInput(inputId = "AC2",
                              label = "AC:",
                              min = 1,
                              step = 1,
                              value = 12, 
                              width = '75%'),
                 numericInput(inputId = "STR2",
                              label = "STR:",
                              min = 0,
                              step = 1,
                              value = 14, 
                              width = '75%'),
                 numericInput(inputId = "DEX2",
                              label = "DEX:",
                              min = 0,
                              step = 1,
                              value = 14, 
                              width = '75%'))),
        conditionalPanel(input$nGroups >=3,
                         tabPanel(title = "Group 3", 
                         p("Use this panel to specify the details of this party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group3",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople3",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK3",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG3",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax3",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC3",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR3",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX3",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=4,
                         tabPanel(title = "Group 4", 
                         p("Use this panel to specify the details of this party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group4",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople4",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK4",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG4",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax4",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC4",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR4",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX4",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
                conditionalPanel(input$nGroups >=5,
                                 tabPanel(title = "Group 5", 
                         p("Use this panel to specify the details of this party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group5",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople5",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK5",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG5",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax5",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC5",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR5",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX5",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=6,
                         tabPanel(title = "Group 6", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group6",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople6",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK6",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG6",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax6",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC6",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR6",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX6",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=7,
                         tabPanel(title = "Group 7", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group7",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople7",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK7",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG7",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax7",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC7",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR7",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX7",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=8,
                         tabPanel(title = "Group 8", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group8",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople8",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK8",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG8",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax8",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC8",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR8",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX8",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=9,
                         tabPanel(title = "Group 9", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group9",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople9",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK9",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG9",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax9",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC9",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR9",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX9",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=10,
                         tabPanel(title = "Group 10", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group10",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople10",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK10",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG10",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax10",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC10",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR10",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX10",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=11,
                         tabPanel(title = "Group 11", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group11",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople11",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK11",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG11",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax11",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC11",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR11",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX11",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=12,
                         tabPanel(title = "Group 12", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group12",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople12",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK12",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG12",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax12",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC12",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR12",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX12",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=13,
                         tabPanel(title = "Group 13", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group13",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople13",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK13",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG13",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax13",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC13",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR13",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX13",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=14,
                         tabPanel(title = "Group 14", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group14",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople14",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK14",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG14",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax14",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC14",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR14",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX14",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=15,
                         tabPanel(title = "Group 15", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group15",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople15",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK15",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG15",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax15",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC15",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR15",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX15",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'))),
        conditionalPanel(input$nGroups >=16,
                         tabPanel(title = "Group 16", 
                         p("Use this panel to specify the details of your fighters from the fourth party"),                 
                         br(),
                         # Input: Text entry to specify group names ----
                         textInput(inputId = "group16",
                                   label = "Name:",
                                   value = NA,
                                   placeholder = NA, 
                                   width = '75%'),
                         # Input: Numeric entry to specify group sizes ----                 
                         numericInput(inputId = "nPeople16",
                                      label = "Group Size:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         # Input: Numeric entry to simulate attack bonuses ----
                         numericInput(inputId = "ATK16",
                                      label = "ATK Bonus:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         textInput(inputId = "DMG16",
                                   label = "Damage Dice:",
                                   placeholder = NA,
                                   value = NA, 
                                   width = '75%'),
                         numericInput(inputId = "HPmax16",
                                      label = "HP max:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "AC16",
                                      label = "AC:",
                                      min = 1,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "STR16",
                                      label = "STR:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%'),
                         numericInput(inputId = "DEX16",
                                      label = "DEX:",
                                      min = 0,
                                      step = 1,
                                      value = NA, 
                                      width = '75%')))
      ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      h2("Simulation Results", align='center'),
      tabsetPanel(
        tabPanel(title = "Turn-By-Turn Summary", 
                 p("This is a report of all of the events that occurred during the simulation. 
                   The output contained here can be modified using the", strong("Turn-By-Turn Output"), 
                   "indicator on the side panel."),                 
                 br(), 
                 p(strong("Coming Soon:"), "Output downloads in .csv format"),
                 downloadButton('downloadSummary',"Download the summary"),
                 br(),
                 br(),
                 # Output: Table of the details of the fighters after the simulation ----
                 tableOutput(outputId = "summary")
                 ),
        tabPanel(title = "Combatant Stats", 
                 p("This is a table detailing the status of each fighter at the conclusion of the battle. 
                   The table is interactive and can be searched or sorted."),
                 br(), 
                 p(strong("Coming Soon:"), "Output downloads in .csv format"),
                 downloadButton('downloadTable',"Download the data"),
                 br(),
                 br(),
                 # Output: Table of the details of the fighters after the simulation ----
                 dataTableOutput(outputId = "table")
                 )
        )
      )
    )


# Source: The primary simulation function
source('PartySim.R')
source('CombatSim.R')

# Define server ----
server <- function(input, output) {
  
    df <- reactive({
      if (input$nGroups == 2){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2),
                           nPeople = c(input$nPeople1,input$nPeople2),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1,input$ATK2),
                           DMG = c(input$DMG1, input$DMG2),
                           HPmax = c(input$HPmax1, input$HPmax2),
                           AC = c(input$AC1, input$AC2),
                           Seed = input$Seed))
      }
      if (input$nGroups == 3){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3),
                           AC = c(input$AC1, input$AC2, input$AC3),
                           STR = c(input$STR1, input$STR2, input$STR3),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3),
                           Seed = input$Seed))
      }
      if (input$nGroups == 4){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4),
                           Seed = input$Seed))
      }
      if (input$nGroups == 5){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5),
                           Seed = input$Seed))
      }
      if (input$nGroups == 6){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6),
                           Seed = input$Seed))
      }
      if (input$nGroups == 7){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7),
                           Seed = input$Seed))
      }
      if (input$nGroups == 8){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7, input$group8),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7, input$nPeople8),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7, input$ATK8),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7, input$DMG8),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7, input$HPmax8),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7, input$AC8),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7, input$STR8),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7, input$DEX8),
                           Seed = input$Seed))
      }
      if (input$nGroups == 9){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7, input$group8,
                                         input$group9),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7, input$nPeople8,
                                       input$nPeople9),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7, input$ATK8,
                                   input$ATK9),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7, input$DMG8,
                                   input$DMG9),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7, input$HPmax8,
                                     input$HPmax9),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7, input$AC8,
                                  input$AC9),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7, input$STR8,
                                   input$STR9),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7, input$DEX8,
                                   input$DEX9),
                           Seed = input$Seed))
      }
      if (input$nGroups == 10){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7, input$group8,
                                         input$group9, input$group10),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7, input$nPeople8,
                                       input$nPeople9, input$nPeople10),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7, input$ATK8,
                                   input$ATK9, input$ATK10),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7, input$DMG8,
                                   input$DMG9, input$DMG10),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7, input$HPmax8,
                                     input$HPmax9, input$HPmax10),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7, input$AC8,
                                  input$AC9, input$AC10),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7, input$STR8,
                                   input$STR9, input$STR10),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7, input$DEX8,
                                   input$DEX9, input$DEX10),
                           Seed = input$Seed))
      }
      if (input$nGroups == 11){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7, input$group8,
                                         input$group9, input$group10, input$group11),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7, input$nPeople8,
                                       input$nPeople9, input$nPeople10, input$nPeople11),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7, input$ATK8,
                                   input$ATK9, input$ATK10, input$ATK11),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7, input$DMG8,
                                   input$DMG9, input$DMG10, input$DMG11),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7, input$HPmax8,
                                     input$HPmax9, input$HPmax10, input$HPmax11),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7, input$AC8,
                                  input$AC9, input$AC10, input$AC11),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7, input$STR8,
                                   input$STR9, input$STR10, input$STR11),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7, input$DEX8,
                                   input$DEX9, input$DEX10, input$DEX11),
                           Seed = input$Seed))
      }
      if (input$nGroups == 12){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7, input$group8,
                                         input$group9, input$group10, input$group11, input$group12),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7, input$nPeople8,
                                       input$nPeople9, input$nPeople10, input$nPeople11, input$nPeople12),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7, input$ATK8,
                                   input$ATK9, input$ATK10, input$ATK11, input$ATK12),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7, input$DMG8,
                                   input$DMG9, input$DMG10, input$DMG11, input$DMG12),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7, input$HPmax8,
                                     input$HPmax9, input$HPmax10, input$HPmax11, input$HPmax12),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7, input$AC8,
                                  input$AC9, input$AC10, input$AC11, input$AC12),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7, input$STR8,
                                   input$STR9, input$STR10, input$STR11, input$STR12),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7, input$DEX8,
                                   input$DEX9, input$DEX10, input$DEX11, input$DEX12),
                           Seed = input$Seed))
      }
      if (input$nGroups == 13){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7, input$group8,
                                         input$group9, input$group10, input$group11, input$group12,
                                         input$group13, input$group14, input$group15, input$group16),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7, input$nPeople8,
                                       input$nPeople9, input$nPeople10, input$nPeople11, input$nPeople12,
                                       input$nPeople13),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7, input$ATK8,
                                   input$ATK9, input$ATK10, input$ATK11, input$ATK12,
                                   input$ATK13),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7, input$DMG8,
                                   input$DMG9, input$DMG10, input$DMG11, input$DMG12,
                                   input$DMG13),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7, input$HPmax8,
                                     input$HPmax9, input$HPmax10, input$HPmax11, input$HPmax12,
                                     input$HPmax13),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7, input$AC8,
                                  input$AC9, input$AC10, input$AC11, input$AC12,
                                  input$AC13),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7, input$STR8,
                                   input$STR9, input$STR10, input$STR11, input$STR12,
                                   input$STR13),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7, input$DEX8,
                                   input$DEX9, input$DEX10, input$DEX11, input$DEX12,
                                   input$DEX13),
                           Seed = input$Seed))
      }
      if (input$nGroups == 14){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7, input$group8,
                                         input$group9, input$group10, input$group11, input$group12,
                                         input$group13, input$group14),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7, input$nPeople8,
                                       input$nPeople9, input$nPeople10, input$nPeople11, input$nPeople12,
                                       input$nPeople13, input$nPeople14),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7, input$ATK8,
                                   input$ATK9, input$ATK10, input$ATK11, input$ATK12,
                                   input$ATK13, input$ATK14),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7, input$DMG8,
                                   input$DMG9, input$DMG10, input$DMG11, input$DMG12,
                                   input$DMG13, input$DMG14),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7, input$HPmax8,
                                     input$HPmax9, input$HPmax10, input$HPmax11, input$HPmax12,
                                     input$HPmax13, input$HPmax14),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7, input$AC8,
                                  input$AC9, input$AC10, input$AC11, input$AC12,
                                  input$AC13, input$AC14),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7, input$STR8,
                                   input$STR9, input$STR10, input$STR11, input$STR12,
                                   input$STR13, input$STR14),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7, input$DEX8,
                                   input$DEX9, input$DEX10, input$DEX11, input$DEX12,
                                   input$DEX13, input$DEX14),
                           Seed = input$Seed))
      }
      if (input$nGroups == 15){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7, input$group8,
                                         input$group9, input$group10, input$group11, input$group12,
                                         input$group13, input$group14, input$group15),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7, input$nPeople8,
                                       input$nPeople9, input$nPeople10, input$nPeople11, input$nPeople12,
                                       input$nPeople13, input$nPeople14, input$nPeople15),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7, input$ATK8,
                                   input$ATK9, input$ATK10, input$ATK11, input$ATK12,
                                   input$ATK13, input$ATK14, input$ATK15),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7, input$DMG8,
                                   input$DMG9, input$DMG10, input$DMG11, input$DMG12,
                                   input$DMG13, input$DMG14, input$DMG15),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7, input$HPmax8,
                                     input$HPmax9, input$HPmax10, input$HPmax11, input$HPmax12,
                                     input$HPmax13, input$HPmax14, input$HPmax15),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7, input$AC8,
                                  input$AC9, input$AC10, input$AC11, input$AC12,
                                  input$AC13, input$AC14, input$AC15),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7, input$STR8,
                                   input$STR9, input$STR10, input$STR11, input$STR12,
                                   input$STR13, input$STR14, input$STR15),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7, input$DEX8,
                                   input$DEX9, input$DEX10, input$DEX11, input$DEX12,
                                   input$DEX13, input$DEX14, input$DEX15),
                           Seed = input$Seed))
      }
      if (input$nGroups == 16){
        (table <- PartySim(nGroups = input$nGroups,
                           GroupName = c(input$group1, input$group2, input$group3, input$group4,
                                         input$group5, input$group6, input$group7, input$group8,
                                         input$group9, input$group10, input$group11, input$group12,
                                         input$group13, input$group14, input$group15, input$group16),
                           nPeople = c(input$nPeople1, input$nPeople2, input$nPeople3, input$nPeople4,
                                       input$nPeople5, input$nPeople6, input$nPeople7, input$nPeople8,
                                       input$nPeople9, input$nPeople10, input$nPeople11, input$nPeople12,
                                       input$nPeople13, input$nPeople14, input$nPeople15, input$nPeople16),
                           Uniform = input$Uniform,
                           ATK = c(input$ATK1, input$ATK2, input$ATK3, input$ATK4,
                                   input$ATK5, input$ATK6, input$ATK7, input$ATK8,
                                   input$ATK9, input$ATK10, input$ATK11, input$ATK12,
                                   input$ATK13, input$ATK14, input$ATK15, input$ATK16),
                           DMG = c(input$DMG1, input$DMG2, input$DMG3, input$DMG4,
                                   input$DMG5, input$DMG6, input$DMG7, input$DMG8,
                                   input$DMG9, input$DMG10, input$DMG11, input$DMG12,
                                   input$DMG13, input$DMG14, input$DMG15, input$DMG16),
                           HPmax = c(input$HPmax1, input$HPmax2, input$HPmax3, input$HPmax4,
                                     input$HPmax5, input$HPmax6, input$HPmax7, input$HPmax8,
                                     input$HPmax9, input$HPmax10, input$HPmax11, input$HPmax12,
                                     input$HPmax13, input$HPmax14, input$HPmax15, input$HPmax16),
                           AC = c(input$AC1, input$AC2, input$AC3, input$AC4,
                                  input$AC5, input$AC6, input$AC7, input$AC8,
                                  input$AC9, input$AC10, input$AC11, input$AC12,
                                  input$AC13, input$AC14, input$AC15, input$AC16),
                           STR = c(input$STR1, input$STR2, input$STR3, input$STR4,
                                   input$STR5, input$STR6, input$STR7, input$STR8,
                                   input$STR9, input$STR10, input$STR11, input$STR12,
                                   input$STR13, input$STR14, input$STR15, input$STR16),
                           DEX = c(input$DEX1, input$DEX2, input$DEX3, input$DEX4,
                                   input$DEX5, input$DEX6, input$DEX7, input$DEX8,
                                   input$DEX9, input$DEX10, input$DEX11, input$DEX12,
                                   input$DEX13, input$DEX14, input$DEX15, input$DEX16),
                           Seed = input$Seed))
      }
    })

      # Rendering: Table output of the fighters ----
      output$table <- DT::renderDataTable({
        
          (table <- CombatSim(df = df(),
                              Output = "Table",
                              Ending = input$Ending,
                              nRounds = input$nRounds,
                              PlayByPlay = input$PlayByPlay,
                              Seed = input$Seed))
      })
      output$downloadTable <- downloadHandler(
                                         filename = function(){"df.csv"}, 
                                         content = function(fname){
                                         write.csv(df(), fname)
    }
  )
      
      # Rendering: Text output of the battle summary ----     
      output$summary <- renderTable({
        
          (summary <- CombatSim(df = df(),
                              Output = "Text",
                              Ending = input$Ending,
                              nRounds = input$nRounds,
                              PlayByPlay = input$PlayByPlay,
                              Seed = input$Seed))
      })
}

# Run the application 
shinyApp(ui = ui, server = server)