## CombatSim.R v1.1 - 2022.01.05 

# Values present represent defaults which can be modified as needed. Only value required is Groups.
CombatSim <- function(df, #Dataframe generated by FighterSim or mirroring its column structure.
                      Side = NA, # A list() of parties who stand in opposition to one another during the battle. Can be ignored if all groups are fighting each other. Any groups on the same side should have their names concatenated together.
                      Output = "Table", #Determines what the object produced by this function is; text (Summary of actions) or table (Data)
                      Ending = "Death", #Logical statement that will dictate how many rounds the simulation should run. "Death" will run until all members of a group have been terminated. "Timed" will run for a number of rounds you specify in the "nRounds" command.
                      nRounds = NA, #The number of rounds that the simulation should run if the ending is "Timed".
                      PlayByPlay = "Off",  #Command that will include output of what happens on each turn. Possibly options include "Kills", "Attacks", "Everything", "Off"
                      Seed = sample(0:99999, size = 1)) #Seed value, which if entered, allows the user to reliably generate the same simulated characters repeatedly.
{ 
  
  df = df #Dataframe generated by FighterSim or mirroring its column structure.
  Side = list(good = c("A", "C")) # A list() of parties who stand in opposition to one another during the battle. Can be ignored if all groups are fighting each other. Any groups on the same side should have their names concatenated together.
  Output = "Table" #Determines what the object produced by this function is; text (Summary of actions) or table (Data)
  Ending = "Death" #Logical statement that will dictate how many rounds the simulation should run. "Death" will run until all members of a group have been terminated. "Timed" will run for a number of rounds you specify in the "nRounds" command.
  nRounds = NA #The number of rounds that the simulation should run if the ending is "Timed".
  PlayByPlay = "Off"  #Command that will include output of what happens on each turn. Possibly options include "Kills", "Attacks", "Everything", "Off"
  Seed = sample(0:99999, size = 1) #Seed value, which if entered, allows the user to reliably generate the same simulated characters repeatedly.
    
  
  # Options ----
  options(warn=-1)
  
  # Packages ----
  library(tidyverse)
  
  # Dependent Functions ----
  source('C:/Users/Administrator/Desktop/Scripts/DnDRuf/dev/v1.1/SupportFunctions/rollr.R')
  source('C:/Users/Administrator/Desktop/Scripts/DnDRuf/dev/v1.1/InitiatSim.R')

  # Errors ----
  
  # Specifying Necessary Rows and Formatting ----
  vars <- c('Name', 'Group', 'ATK', 'DMG', 'HPmax', 'AC')
  cols <- paste("df", vars, sep = "$")
  
  ## Column Names Do Not Follow Required Format ----
  for (i in vars){
    if (!i %in% colnames(df)){
      stop(paste0("No column in the dataframe that you had submitted is named ", i, ". 
                    CombatSim() must be able to read data from column ", i, " to function 
                    properly. See PartySim() Output specifications for an example."),
           call. = F)
    }
  }
  
  ## Column Values Contain NA Values ----
  for (i in cols){
    if (any(is.na(eval(parse(text = i)))) == TRUE){
      stop(paste0("Column ", i, " in this dataframe does no have readable data.
                    CombatSim() must be able to read data from column ", i, " to function
                    properly. See PartySim() Output specifications for an example."),
           call. = F)
    }
  }
  
  ## Numeric Columns Are Not Formatted Correctly ----
  for (i in cols[c(3,5,6)]){
    if (any(!is.numeric(eval(parse(text = i)))) == TRUE){
      stop(paste0("Column ", i, " in this dataframe is not structured as a numeric variable.
                   CombatSim() must be able to read numeric data from column ", i, " to function
                   properly. Please reformat column ", i," and rerun the function."),
           call. = F)
    }
  }
  
  ## DMG Column Is Not Formatted Properly ----
  for (i in cols[4]){
    if (any(!str_detect(string = eval(parse(text = i)),
                    pattern = ".d.")) == TRUE){
      stop(paste0( i, " column must contain the damage dice a character will roll 
                   should their attack hit. This typically takes the format '#d#',
                   or '#d# + #' in the event bonuses are added. Column ", i, " must
                   be formatted in this way for CombatSim() to function properly. 
                   Please reformat column ", i," and rerun the function, or look to
                   PartySim() for more specification details."),
           call. = F)
    }
  }
  
  ## Output Input is Not Recognized ----
  if (Output != "Table" & Output != "Text"){
    stop(paste0("Output can only take the values: 'Table' or 'Text'. You have entered: ", Output,
                " Note: entries are case-sensitive and must be in string format."),
         call. = F)
  }
  
  ## Ending Input is Not Recognized ----
  if (Ending != "Death" & Ending != "Timed"){
    stop(paste0("Ending can only take the values: 'Death' or 'Timed'. You have entered: ", Ending,
                " Note: entries are case-sensitive and must be in string format."),
         call. = F)
  }
  
  ## PlayByPlay Input is Not Recognized ----
  if (PlayByPlay != "Off" & PlayByPlay != "Kills" & PlayByPlay != "Attacks" & PlayByPlay != "Everything" ){
        stop(paste0("PlayByPlay can only take the values: 'Off', 'Kills', 'Attacks', or 'Everything'. You have entered: ", 
                    PlayByPlay, " Note: entries are case-sensitive and must be in string format."),
             call. = F)
  }
  
  ## nRounds Input is Either Non-Numeric or Negative
  if (!is.na(nRounds)){
    if (!is.numeric(nRounds) | nRounds <= 0){
      stop(paste0("nRounds must take a numeric value of 1 or greater. You have entered: ", 
                nRounds),
         call. = F)
    }
  }
  
  ## Seed Input is Either Non-Numeric or Negative
  if (!is.na(Seed)){
    if (!is.numeric(Seed) | Seed < 0){
      stop(paste0("Seed must take a numeric value of 0 or greater. You have entered: ", 
                  Seed),
           call. = F)
    }
  }
  
# Function Start -----
 
  # Seeding Random Generators -----
  if (!is.na(Seed)){
    # Setting the seed the allows us to regenerate the same simulations again and again
    set.seed(Seed)
    # Printing tha value so that the user has it, should they want it in the future.
    print(paste0("Seed: ", Seed))
  }
  
  # Defining Variables ----
  ## Characters ----
  # The number of characters battling
  characters <- 1:length(rownames(df))
  
  ## Groups ----
  # Simply the unique names provided within the dataframe column Group
  Groups <- unique(df$Group)
  
  ## Sides ----
  # If 'Sides' has been defined, we iterate through each element in the list and 
  # assign them letters which R will use to keep track of who is fighting who. 
  if (!is.na(Side)){
    df$Side <- NA
    for (i in 1:length(Side)){
      for (k in Groups){
        if (any(k == Side[[i]])){
          df$Side[df$Group == k] <- LETTERS[i]
        }
      } 
    }
    for (i in unique(df$Group[is.na(df$Side)])){
      df$Side[df$Group == i] <- LETTERS[length(unique(df$Side))]
    }
  }
  
  # If 'Sides' is undefined, it is assumed all groups are fighting against all 
  # other groups, so one's Group' just becomes one's 'Side'
  if (is.na(Side)){
    df$Side <- df$Group
  }
  
  # We then define a variable separate from the column, which is helpful when need
  # to iterate through these variables later.
  Sides <- unique(df$Side)

  ## Group Sizes ----
  # This function will simply output an array containing the number of combatants 
  # belonging to any given group, which, again, will be helpful for checking which
  # groups are still in the fight later. 
  GrpSize <- function(input,
                      source,
                      output){
    variable <- NA
    for (i in 1:length(input)){
      variable <- c(variable, length(unique(output[source == input[i]])))
    }
    variable <- variable[-1]
    return(variable)
  }
  
  # Now we are defining variables for Group Size and Side Size 
  nPeopleGrp <- GrpSize(input = Groups,
                        source = df$Group,
                        output = df$Name)
  nPeopleSde <- GrpSize(input = Sides,
                        source = df$Side,
                        output = df$Name)
  
  ## Variables Modified Within Loop ----
  # R demands that variables in a loop be first defined outside of that loop. It's
  # slightly annoying, but I get it, so these variables will just take a nonsense
  # NA value until further defined later in the loop. 
  
  ### ATK ---- 
  # ATK will contain a given character's attack bonus score
  ATK <- NA
  
  ### DMG ----
  # DMG will contain a given character's DMG dice and modifiers
  DMG <- NA
  
  ### DeathSave ----
  # DeathSave will contain a given character's roll after being subdued towards life or death
  DeathSave <- NA
  
  ### Summary ----
  # Summary will contain text descriptions of all of the events 
  Summary <- NA
  
  # Tracking what round fighters were killed in
  df$RoundKilled <- NA
  
  # Defining New Columns ----
  ## Life Status ----
  # Will track whether a character is still in battle or not
  df$LifeStatus <- "Alive"
  
  ## HP ----
  # Will track how many hit points a character still has
  df$HP <- df$HPmax
  
  ## Engagement ----
  # Tracking who fighters are engaged with
  df$EngagedWith <- NA
  
  ### Kills
  # Tracking who fighters are engaged with
  df$EnemiesKilled <- 0
  
  # Initiative ----
  # Will track the order of action
  df <- InitiatSim(df = df)
  
  # Death Save Tracking ----
  # Tracking the outcomes of death saves for each character
  cols <- c("Name", "Saved","Failed")
  df_deathsaves <- data.frame(matrix(0, 
                                     nrow = length(rownames(df)), 
                                     ncol = length(cols), 
                                     dimnames = list(1:length(rownames(df)), cols)))
  df_deathsaves$Name <- df$Name
  
  # Convenience Functions ----
  ## Engagement ----
  # This function will avoid redundancies and human error by determining who characters
  # are engaging with and then noting such in the action log.
  engage <- function(df = df,
                     person = k,
                     output)
  { 
    # Randomly select a person on an opposing side who is alive to engage with
    df$EngagedWith[person] <- sample(df$Name[(df$Side != df$Side[person]) & df$LifeStatus == "Alive"], 1)
    # Routing output based upon text or table, because I can;t do both simultaneously
    if (output = "text"){
      # Output a text message describing what's happening
      Action <- paste0(df$Name[person], " (", df$Group[person], ")", " has targeted ", df$EngagedWith[person], ".")
      # Output that message is PlayByPlay is desired 
      if (PlayByPlay == "Everything"){
        Summary <- c(Summary, Action)
      }
      return(Summary)
    }
    if (output = "table"){
      return(df)
    }
  }
  
  ## Death ----
  # This function will also avoid redundancies and human error in tracking what happens 
  # when characters die
  death <- function(df = df,
                    person = k,
                    desc = NA,
                    suicide = FALSE,
                    output)
  {
    # If the person kills themselves
    if (suicide = TRUE){
      # Reduce the person's health to 0
      df$HP[df$Name == df$Name[person]] <- 0
      # Change their health status to unconscious
      df$LifeStatus[df$Name == df$Name[person]] <- "Unconscious"
      # Note which round they went down in
      df$RoundKilled[df$Name == df$Name[person]] <- Round
    }
    # If the person kills someone else
    if (suicide = FALSE){
      # Reduce target's health to 0
      df$HP[df$Name == df$EngagedWith[k]] <- 0
      # Change their life status to unconscious
      df$LifeStatus[df$Name == df$EngagedWith[person]] <- "Unconscious"
      # Note what round they went down in
      df$RoundKilled[df$Name == df$EngagedWith[person]] <- Round
      # Increase their kill count by 1
      df$EnemiesKilled[df$Name == df$Name[person]] <- df$EnemiesKilled[df$Name == df$Name[person]] + 1
    }
    # Routing output based upon text or table, because I can;t do both simultaneously
    if (output = "text"){
      # Record what happened in the text tracker
      Action <- desc
      # Output that message is PlayByPlay is desired 
      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
        Summary <- c(Summary, Action)    
      }
      return(Summary)
    }
    if (output = "table"){
      return(df)
    }
  }
  
  # Deathmatch Simulation ----
  if (Ending == "Death"){
    # Create a round tracker set to 0
    Round <- 0
    # Create a life tracker for each group, which takes the form of an array of length Groups.
    # When all members of a group are subdued, their respective tracker will change to value FALSE
    SideAlive <- NA
    SideAlive[1:length(Sides)] <- TRUE
    GroupAlive[1:length(Groups)] <- TRUE
    # During each round of battle (however many it may take)...
    while (length(grep(TRUE, SideAlive)) > 1){
      Round <- Round + 1
      # ... For each initiative position ....
      for (j in sort(unique(df$InitiativeOrder))){
        # ... For each battle participant ....
        for (k in characters){
          # Check whether any groups have lost all of their members so far and change the tracker if so
          for (z in 1:length(Groups)){
            if (sum(df$LifeStatus != "Alive" & df$Side == Sides[z]) == nPeopleSde[z])
              SideAlive[z] <- FALSE
          }
          # ... skip over participants that don't have priority initiative.
          if (df$InitiativeOrder[k] == j){
            # ... and check whether they are currently alive. 
            if (df$LifeStatus[k] == "Alive"){
              # Check whether any groups have lost all of their members so far and change the tracker if so
              for (z in 1:length(Sides)){
                if (sum(df$LifeStatus != "Alive" & df$Side == Sides[z]) == nPeopleSde[z])
                  SideAlive[z] <- FALSE
              }
              # if the opposing party is dead, cease this turn.
              if (length(grep(TRUE, SideAlive)) == 1){
                break}
              # if the opposing party is alive, continue this turn.
              if (length(grep(TRUE, SideAlive)) > 1){
                # If someone has not engaged, randomly choose someone to attack.            
                if (is.na(df$EngagedWith[k])){
                  df <- engage(output = "table")
                  Summary <- engage(output = "text")
                  }
                }        
                # If the person they were previously engaged with died, randomly choose someone else to attack.            
                if (!is.na(df$EngagedWith[k]) & df$LifeStatus[df$Name == df$EngagedWith[k]] != "Alive"){
                  df <- engage(output = "table")
                  Summary <- engage(output = "text")
                  }
                }
                # If someone is engaged with someone, let them try to attack..            
                if (!is.na(df$EngagedWith[k]) & df$LifeStatus[df$Name == df$EngagedWith[k]] == "Alive"){
                  ATK <- roll_dice("1d20")
                  # ... if they roll a Natural 1, they'll inflict damage on themselves
                  if (ATK == 1){
                    DMG <- roll_dice(df$DMG[k])
                    df$HP[df$Name == df$Name[k]] <- df$HP[df$Name == df$Name[k]] - DMG
                    Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but hurt themselves in the process and took ", DMG, " points of damage.")
                    if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                      Summary <- c(Summary, Action)
                    }
                    # ... and if their HP drops below 0 as a result, they will be knocked unconscious.                
                    if (df$HP[df$Name == df$Name[k]] <= 0){
                      df <- death(suicide = TRUE,
                                  output = "table")
                      df <- death(desc = paste0(df$Name[k], " (", df$Group[k], ")", " has accidentally committed suicide!"),
                                  suicide = TRUE,
                                  output = "text")
                    }
                  }
                  # ... if they roll a Natural 20,
                  if (ATK == 20){
                    ATK <- roll_dice("1d20")
                    # ... they get the chance to roll twice more
                    if (ATK == 20){
                      ATK <- roll_dice("1d20")
                      # ,,, and if they successfully roll two more 20s
                      if (ATK == 20){
                        # They will kill their opponent in a single swing.
                        df <- death(output = "table")
                        df <- death(desc = paste0("In an unparalleled display of brutality and carnage, ", df$Name[k], " (", df$Group[k], ")", " has annihilated ", df$EngagedWith[k]," with a single attack."),
                                    output = "text")
                      }
                    }
                    # ... if they do not roll another 20, though, they will still do double damage.
                    if (ATK != 20){
                      DMG <- (roll_dice(df$DMG[k]) * 2)
                      df$HP[df$Name == df$EngagedWith[k]] <- df$HP[df$Name == df$EngagedWith[k]] - DMG
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k]," and done critical damage, at ", DMG, " points total.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                      # ... and if their target's HP drops below 0 as a result, they will be knocked unconscious.  
                      if (df$HP[df$Name == df$EngagedWith[k]] <= 0){
                        df <- death(output = "table")
                        df <- death(desc = paste0("After taking a critical hit, ", df$EngagedWith[k], " (", df$Group[df$Name == df$EngagedWith[k]], ")", " has fallen!"),
                                    output = "text")
                      }
                    }
                  }
                  # ... and if their attack roll is somewhere in the middle...
                  if (ATK > 1 & ATK < 20){
                    # ... add their attack modifier
                    ATK <- ATK + df$ATK[k]
                    # ... if the attack roll is greater than their target's AC, roll damage.
                    if (ATK > df$AC[df$Name == df$EngagedWith[k]]){
                      DMG <- roll_dice(df$DMG[k])
                      df$HP[df$Name == df$EngagedWith[k]] <- df$HP[df$Name == df$EngagedWith[k]] - DMG
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k]," and done ", DMG, " points of damage.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                      # ... and if their target's HP drops below 0 as a result, they will be knocked unconscious. 
                      if (df$HP[df$Name == df$EngagedWith[k]] <= 0){
                        df <- death(output = "table")
                        df <- death(desc = paste0(df$EngagedWith[k], " (", df$Group[df$Name == df$EngagedWith[k]], ")", " has gone down!"),
                                    output = "text")
                      }
                    }
                    # ... if the attack roll is less than or equal to their target's AC, the attack misses.
                    if (ATK < df$AC[df$Name == df$EngagedWith[k]]){
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but missed.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                    }
                    if (ATK == df$AC[df$Name == df$EngagedWith[k]]){
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but ", df$EngagedWith[k], " just barely escaped without damage.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                    }              
                  }
                }
              }
            }
            # ... and check whether they are currently unconscious.
            if (df$LifeStatus[k] == "Unconscious"){
              # If so, roll a death save...
              DeathSave <- roll_dice("1d20")
              # If the roll a 1, take two failures
              if (DeathSave == 1){
                df_deathsaves$Failed[k] <- df_deathsaves$Failed[k] + 2
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved dramatically closer to death.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll a 20, take two successes
              if (DeathSave == 20){
                df_deathsaves$Saved[k] <- df_deathsaves$Saved[k] + 2
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved dramatically closer to life.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll less than an 11, take one failure
              if (DeathSave > 1 & DeathSave < 11){
                df_deathsaves$Failed[k] <- df_deathsaves$Failed[k] + 1
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved one step closer to death.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll greater than a 10, take one success.
              if (DeathSave > 10 & DeathSave < 20){
                df_deathsaves$Saved[k] <- df_deathsaves$Saved[k] + 1
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved one step closer to life.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              if (df_deathsaves$Saved[k] >= 3){
                df_deathsaves$Saved[k] <- 0
                df_deathsaves$Failed[k] <- 0
                df$LifeStatus[k] <- "Stable"
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has stabilized and avoided death.")
                if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                  Summary <- c(Summary, Action)                    
                }
              }
              if (df_deathsaves$Failed[k] >= 3){
                df_deathsaves$Saved[k] <- 0
                df_deathsaves$Failed[k] <- 0
                df$LifeStatus[k] <- "Dead"
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has succumbed to their injuries and died.")
                if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # Check whether any groups have lost all of their members so far and change the tracker if so
              for (z in 1:length(Sides)){
                if (sum(df$LifeStatus != "Alive" & df$Side == Sides[z]) == nPeopleSde[z])
                  SideAlive[z] <- FALSE
              }
            }
          }
    }

    # Removing the NA value we needed to start the Summary variable
    Summary <- Summary[-1]
    # Displaying the Play By Play if it was requested
    if (PlayByPlay != "Off"){
      print(Summary)
    }
  
    # Displaying the final summary of the battle.
    Conclusion <- paste("The battle has ended!", Round, "rounds have passed!", sep = " ")
    if (sum(df$LifeStatus != "Alive" & df$Group == Groups[z]) == nPeopleGrp[z]){
      GroupAlive[z] <- FALSE
    }
    for (i in 1:length(Groups)){
      if (GroupAlive[i] == FALSE){
        Conclusion <- paste(Conclusion, paste("All members of", Groups[i], "have fallen.", sep= " "), sep = " ")
      }
      if (GroupAlive[i] == TRUE){  
        Conclusion <- paste(Conclusion, paste(sum(df$LifeStatus == "Alive" & df$Group == Groups[i]), "members of", Groups[i], "remain!", sep= " "))
      }
    }
  }

  # Timed Simulation ----
  if (Ending == "Timed"){
    # Create a life tracker for each group, which takes the form of an array of length Groups.
    # When all members of a group are subdued, their respective tracker will change to value FALSE
    SideAlive <- NA
    SideAlive[1:length(Sides)] <- TRUE 
    GroupAlive[1:length(Groups)] <- TRUE 
    # During each round of battle (however many it may take)...
    for (i in 1:nRounds){
      # ... For each initiative position ....
      for (j in sort(unique(df$InitiativeOrder))){
        # ... For each battle participant ....
        for (k in characters){
          # Check whether any groups have lost all of their members so far and change the tracker if so
          for (z in 1:length(Sides)){
            if (sum(df$LifeStatus != "Alive" & df$Side == Sides[z]) == nPeopleSde[z])
              SideAlive[z] <- FALSE
          }
          # ... skip over participants that don't have priority initiative.
          if (df$InitiativeOrder[k] == j){
            # ... and check whether they are currently alive. 
            if (df$LifeStatus[k] == "Alive"){
              # Check whether any groups have lost all of their members so far and change the tracker if so
              for (z in 1:length(Sides)){
                if (sum(df$LifeStatus != "Alive" & df$Side == Sides[z]) == nPeopleSde[z])
                  SideAlive[z] <- FALSE
              }
              # if there opposing party is dead, cease this turn.
              if (length(grep(TRUE, SideAlive)) == 1){
                break}
              # if there opposing party is alive, continue this turn.
              if (length(grep(TRUE, SideAlive)) > 1){
                # If someone has not engaged, randomly choose someone to attack.            
                if (is.na(df$EngagedWith[k])){
                  df <- engage(output = "table")
                  Summary <- engage(output = "text")
                  }
                }        
                # If the person they were previously engaged with died, randomly choose someone else to attack.            
                if (!is.na(df$EngagedWith[k]) & df$LifeStatus[df$Name == df$EngagedWith[k]] != "Alive"){
                  df <- engage(output = "table")
                  Summary <- engage(output = "text")
                  }
                }
                # If someone is engaged with someone, let them try to attack..            
                if (!is.na(df$EngagedWith[k]) & df$LifeStatus[df$Name == df$EngagedWith[k]] == "Alive"){
                  ATK <- roll_dice("1d20")
                  # ... if they roll a Natural 1, they'll inflict damage on themselves
                  if (ATK == 1){
                    DMG <- roll_dice(df$DMG[k])
                    df$HP[df$Name == df$Name[k]] <- df$HP[df$Name == df$Name[k]] - DMG
                    Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but hurt themselves in the process and took ", DMG, " points of damage.")
                    if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                      Summary <- c(Summary, Action)
                    }
                    # ... and if their HP drops below 0 as a result, they will be knocked unconscious.                
                    if (df$HP[df$Name == df$Name[k]] <= 0){
                      df <- death(output = "table",
                                  suicide = TRUE)
                      df <- death(desc = paste0(df$Name[k], " (", df$Group[k], ")", " has accidentally committed suicide!"),
                                  suicide = TRUE,
                                  output = "text")
                    }
                  }
                  # ... if they roll a Natural 20,
                  if (ATK == 20){
                    ATK <- roll_dice("1d20")
                    # ... they get the chance to roll twice more
                    if (ATK == 20){
                      ATK <- roll_dice("1d20")
                      # ,,, and if they successfully roll two more 20s
                      if (ATK == 20){
                        # They will kill their opponent in a single swing.
                        df <- death(output = "table")
                        df <- death(desc = paste0("In an unparalleled display of brutality and carnage, ", df$Name[k], " (", df$Group[k], ")", " has annihilated ", df$EngagedWith[k]," with a single attack."),
                                    output = "text")
                      }
                    }
                    # ... if they do not roll another 20, though, they will still do double damage.
                    if (ATK != 20){
                      DMG <- (roll_dice(df$DMG[k]) * 2)
                      df$HP[df$Name == df$EngagedWith[k]] <- df$HP[df$Name == df$EngagedWith[k]] - DMG
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k]," and done critical damage, at ", DMG, " points total.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                      # ... and if their target's HP drops below 0 as a result, they will be knocked unconscious.  
                      if (df$HP[df$Name == df$EngagedWith[k]] <= 0){
                        df <- death(output = "table")
                        df <- death(desc = paste0("After taking a critical hit, ", df$EngagedWith[k], " (", df$Group[df$Name == df$EngagedWith[k]], ")", " has fallen!"),
                                    output = "text")
                      }
                    }
                  }
                  # ... and if their attack roll is somewhere in the middle...
                  if (ATK > 1 & ATK < 20){
                    # ... add their attack modifier
                    ATK <- ATK + df$ATK[k]
                    # ... if the attack roll is greater than their target's AC, roll damage.
                    if (ATK > df$AC[df$Name == df$EngagedWith[k]]){
                      DMG <- roll_dice(df$DMG[k])
                      df$HP[df$Name == df$EngagedWith[k]] <- df$HP[df$Name == df$EngagedWith[k]] - DMG
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k]," and done ", DMG, " points of damage.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                      # ... and if their target's HP drops below 0 as a result, they will be knocked unconscious. 
                      if (df$HP[df$Name == df$EngagedWith[k]] <= 0){
                        df <- death(output = "table")
                        df <- death(desc = paste0(df$EngagedWith[k], " (", df$Group[df$Name == df$EngagedWith[k]], ")", " has gone down!"),
                                    output = "text")
                      }
                    }
                    # ... if the attack roll is less than or equal to their target's AC, the attack misses.
                    if (ATK < df$AC[df$Name == df$EngagedWith[k]]){
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but missed.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                    }
                    if (ATK == df$AC[df$Name == df$EngagedWith[k]]){
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but ", df$EngagedWith[k], " just barely escaped without damage.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                    }              
                  }
                }
              }
            }
            # ... and check whether they are currently unconscious.
            if (df$LifeStatus[k] == "Unconscious"){
              # If so, roll a death save...
              DeathSave <- roll_dice("1d20")
              # If the roll a 1, take two failures
              if (DeathSave == 1){
                df_deathsaves$Failed[k] <- df_deathsaves$Failed[k] + 2
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved dramatically closer to death.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll a 20, take two successes
              if (DeathSave == 20){
                df_deathsaves$Saved[k] <- df_deathsaves$Saved[k] + 2
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved dramatically closer to life.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll less than an 11, take one failure
              if (DeathSave > 1 & DeathSave < 11){
                df_deathsaves$Failed[k] <- df_deathsaves$Failed[k] + 1
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved one step closer to death.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll greater than a 10, take one success.
              if (DeathSave > 10 & DeathSave < 20){
                df_deathsaves$Saved[k] <- df_deathsaves$Saved[k] + 1
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved one step closer to life.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              if (df_deathsaves$Saved[k] >= 3){
                df_deathsaves$Saved[k] <- 0
                df_deathsaves$Failed[k] <- 0
                df$LifeStatus[k] <- "Stable"
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has stabilized and avoided death.")
                if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                  Summary <- c(Summary, Action)                    
                }
              }
              if (df_deathsaves$Failed[k] >= 3){
                df_deathsaves$Saved[k] <- 0
                df_deathsaves$Failed[k] <- 0
                df$LifeStatus[k] <- "Dead"
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has succumbed to their injuries and died.")
                if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                  Summary <- c(Summary, Action)                    
                }
              }
            
              # Check whether any groups have lost all of their members so far and change the tracker if so
              for (z in 1:length(Sides)){
                if (sum(df$LifeStatus != "Alive" & df$Side == Sides[z]) == nPeopleSde[z])
                  SideAlive[z] <- FALSE
              }
            }
          }
        }
    
  # Cleaning output ----  
    # Removing the NA value we needed to start the Summary variable
    Summary <- Summary[-1]
    # Displaying the final summary of the battle.
    Conclusion <- paste(nRounds, "rounds have passed!", sep = " ")
    if (sum(df$LifeStatus != "Alive" & df$Group == Groups[z]) == nPeopleGrp[z])
      GroupAlive[z] <- FALSE
    for (i in 1:length(Groups)){
      if (GroupAlive[i] == FALSE){
        Conclusion <- paste(Conclusion, paste("All members of", Groups[i], "have fallen.", sep= " "), sep = " ")
      }
      if (GroupAlive[i] == TRUE){  
        Conclusion <- paste(Conclusion, paste(sum(df$LifeStatus == "Alive" & df$Group == Groups[i]), "members of", Groups[i], "remain!", sep= " "))
      }
    }
  }
  
  # Cleaning Summary output
  Conclusion
  Summary <- c(Summary, Conclusion)
  Summary <- as.data.frame(Summary)
  colnames(Summary[1]) <- "Summary"
  # If we want data fighrer stats
  if (Output == "Table"){
    # Returning the final summary dataframe. 
    return(df)
  }
  # If we want a battle summary
  if (Output == "Text"){
    # Returning the final summary dataframe. 
    return(Summary)
  }
}

df_death <- CombatSim(df = df,
                      Side = list(good = c("A", "C")))