## CombatSim.R v1.1 - 2022.01.05 

# Values present represent defaults which can be modified as needed. Only value required is Groups.
CombatSim <- function(df, #Dataframe generated by FighterSim or mirroring its column structure.
                      Output = "Table", #Determines what the object produced by this function is; text (Summary of actions) or table (Data)
                      Ending = "Death", #Logical statement that will dictate how many rounds the simulation should run. "Death" will run until all members of a group have been terminated. "Timed" will run for a number of rounds you specify in the "nRounds" command.
                      nRounds = NA, #The number of rounds that the simulation should run if the ending is "Timed".
                      PlayByPlay = "Off",  #Command that will include output of what happens on each turn. Possibly options include "Kills", "Attacks", "Everything", "Off"
                      Seed = NA) #Seed value, which if entered, allows the user to reliably generate the same simulated characters repeatedly.
{ options(warn=-1)
  # Dependent functions
  # source('C:/Users/Administrator/Desktop/Personal/Tabletop RPGs/Tabletop_RPG_Tools/DnDRuf/released/v1.1/SupportFunctions/rollr.R')
  # source('C:/Users/Administrator/Desktop/Personal/Tabletop RPGs/Tabletop_RPG_Tools/DnDRuf/released/v1.1/InitiatSim.R')
  source('SupportFunctions/rollr.R')
  source('InitiatSim.R')
  
  # Misspecifications List----
  
  # Checking for possible values for output, ending, and playbyplay
  if (Output != "Table" & Output != "Text"){
    stop(paste0("Output can only take the values: 'Table' or 'Text'. You have entered: ", Output,
                " Note: entries are case-sensitive and must be in string format."),
         call. = F)
  }
  if (Ending != "Death" & Ending != "Timed"){
    stop(paste0("Ending can only take the values: 'Death' or 'Timed'. You have entered: ", Ending,
                " Note: entries are case-sensitive and must be in string format."),
         call. = F)
  }
  if (PlayByPlay != "Off" & PlayByPlay != "Kills" & PlayByPlay != "Attacks" & PlayByPlay != "Everything" ){
        stop(paste0("PlayByPlay can only take the values: 'Off', 'Kills', 'Attacks', or 'Everything'. You have entered: ", 
                    PlayByPlay, " Note: entries are case-sensitive and must be in string format."),
             call. = F)
  }
  if (!is.na(nRounds)){
    if (!is.numeric(nRounds) | nRounds <= 0){
      stop(paste0("nRounds must take a numeric value of 1 or greater. You have entered: ", 
                nRounds),
         call. = F)
    }
  }
  if (!is.na(Seed)){
    if (!is.numeric(Seed) | Seed < 0){
      stop(paste0("Seed must take a numeric value of 0 or greater. You have entered: ", 
                  Seed),
           call. = F)
    }
  }
  
  # Checking for consistency in the length of vectors
  vars <- c('Name', 'Group', 'ATK', 'DMG', 'HPmax', 'AC')
  cols <- paste("df", vars, sep = "$")
  for (i in vars){
    if (!i %in% colnames(df)){
        stop(paste0("No column in the dataframe that you had submitted is named ", i, ". 
                    CombatSim() must be able to read data from column ", i, " to function 
                    properly. See PartySim() Output specifications for an example."),
             call. = F)
    }
  }
  for (i in cols){
    if (any(is.na(eval(parse(text = i)))) == TRUE){
      stop(paste0("Column ", i, " in this dataframe does no have readable data.
                    CombatSim() must be able to read data from column ", i, " to function
                    properly. See PartySim() Output specifications for an example."),
           call. = F)
    }
  }
  
  # No Errors Detected ----
 
  # Setting a seed to reliable generate the same values in the future...
  if (!is.na(Seed)){
    set.seed(Seed)
  }
  # Cleaning the imported dataframe ----
  Groups <- unique(df$Group)
  nPeople <- NA
  for (i in 1:length(Groups)){
    nPeople <- c(nPeople, length(unique(df$Name[df$Group == Groups[i]])))
  }
  nPeople <- nPeople[-1]
  #Variables called within the for loop simulation ----
  ATK <- NA
  DMG <- NA
  DeathSave <- NA
  Summary <- NA
  # The number of people battling
  rows <- 1:length(rownames(df))
  # Adding columns to the dataframe ----
  # Will track whether a character is still in battle or not
  df$LifeStatus <- "Alive"
  # Will track how many hit points a character still has
  df$HP <- df$HPmax
  # Will track the order of action
  df <- InitiatSim(df = df)
  # Tracking who fighters are engaged with
  df$EngagedWith <- NA
  # Tracking who fighters are engaged with
  df$EnemiesKilled <- 0
  # Tracking the outcomes of death saves for each Person
  cols <- c("Name", "Saved","Failed")
  df_deathsaves <- data.frame(matrix(0, 
                          nrow = length(rownames(df)), 
                          ncol = length(cols), 
                          dimnames = list(1:length(rownames(df)), cols)))
  df_deathsaves$Name <- df$Name
  # Tracking what round fighters were killed in
  df$RoundKilled <- NA
  # Deathmatch Simulation ----
  if (Ending == "Death"){
    # Create a round tracker set to 0
    Round <- 0
    # Create a life tracker for each group, which takes the form of an array of length Groups.
    # When all members of a group are subdued, their respective tracker will change to value FALSE
    GroupAlive <- NA
    GroupAlive[1:length(Groups)] <- TRUE 
    # During each round of battle (however many it may take)...
    while (length(grep(TRUE, GroupAlive)) > 1){
      Round <- Round + 1
      # ... For each initiative position ....
      for (j in sort(unique(df$InitiativeOrder))){
        # ... For each battle participant ....
        for (k in rows){
          # Check whether any groups have lost all of their members so far and change the tracker if so
          for (z in 1:length(Groups)){
            if (sum(df$LifeStatus != "Alive" & df$Group == Groups[z]) == nPeople[z])
              GroupAlive[z] <- FALSE
          }
          # ... skip over participants that don't have priority initiative.
          if (df$InitiativeOrder[k] == j){
            # ... and check whether they are currently alive. 
            if (df$LifeStatus[k] == "Alive"){
              # Check whether any groups have lost all of their members so far and change the tracker if so
              for (z in 1:length(Groups)){
                if (sum(df$LifeStatus != "Alive" & df$Group == Groups[z]) == nPeople[z])
                  GroupAlive[z] <- FALSE
              }
              # if the opposing party is dead, cease this turn.
              if (length(grep(TRUE, GroupAlive)) == 1){
                break}
              # if the opposing party is alive, continue this turn.
              if (length(grep(TRUE, GroupAlive)) > 1){
                # If someone has not engaged, randomly choose someone to attack.            
                if (is.na(df$EngagedWith[k])){
                  df$EngagedWith[k] <- sample(df$Name[(df$Group != df$Group[k]) & df$LifeStatus == "Alive"], 1)
                  Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has targeted ", df$EngagedWith[k], ".")
                  if (PlayByPlay == "Everything"){
                    Summary <- c(Summary, Action)                    
                  }
                }        
                # If the person they were previously engaged with died, randomly choose someone else to attack.            
                if (!is.na(df$EngagedWith[k]) & df$LifeStatus[df$Name == df$EngagedWith[k]] != "Alive"){
                  df$EngagedWith[k] <- sample(df$Name[(df$Group != df$Group[k]) & df$LifeStatus == "Alive"], 1)
                  Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has targeted ", df$EngagedWith[k], ".")
                  if (PlayByPlay == "Everything"){
                    Summary <- c(Summary, Action)
                  }
                }
                # If someone is engaged with someone, let them try to attack..            
                if (!is.na(df$EngagedWith[k]) & df$LifeStatus[df$Name == df$EngagedWith[k]] == "Alive"){
                  ATK <- roll_dice("1d20")
                  # ... if they roll a Natural 1, they'll inflict damage on themselves
                  if (ATK == 1){
                    DMG <- roll_dice(df$DMG[k])
                    df$HP[df$Name == df$Name[k]] <- df$HP[df$Name == df$Name[k]] - DMG
                    Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but hurt themselves in the process and took ", DMG, " points of damage.")
                    if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                      Summary <- c(Summary, Action)
                    }
                    # ... and if their HP drops below 0 as a result, they will be knocked unconscious.                
                    if (df$HP[df$Name == df$Name[k]] <= 0){
                      df$HP[df$Name == df$Name[k]] <- 0
                      df$LifeStatus[df$Name == df$Name[k]] <- "Unconscious"
                      df$RoundKilled[df$Name == df$Name[k]] <- Round
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has accidentally committed suicide!")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                        Summary <- c(Summary, Action)
                      }
                    }
                  }
                  # ... if they roll a Natural 20,
                  if (ATK == 20){
                    ATK <- roll_dice("1d20")
                    # ... they get the chance to roll twice more
                    if (ATK == 20){
                      ATK <- roll_dice("1d20")
                      # ,,, and if they successfully roll two more 20s
                      if (ATK == 20){
                        # They will kill their opponent in a single swing.
                        df$HP[df$Name == df$EngagedWith[k]] <- 0
                        df$EnemiesKilled[df$Name == df$Name[k]] <- df$EnemiesKilled[df$Name == df$Name[k]] + 1
                        Action <- paste0("In an unparalleled display of brutality and carnage, ", df$Name[k], " (", df$Group[k], ")", " has annihilated ", df$EngagedWith[k]," with a single attack.")
                        if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                          Summary <- c(Summary, Action)                          
                        }
                      }
                    }
                    # ... if they do not roll another 20, though, they will still do double damage.
                    if (ATK != 20){
                      DMG <- (roll_dice(df$DMG[k]) * 2)
                      df$HP[df$Name == df$EngagedWith[k]] <- df$HP[df$Name == df$EngagedWith[k]] - DMG
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k]," and done critical damage, at ", DMG, " points total.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                      # ... and if their target's HP drops below 0 as a result, they will be knocked unconscious.  
                      if (df$HP[df$Name == df$EngagedWith[k]] <= 0){
                        df$HP[df$Name == df$EngagedWith[k]] <- 0
                        df$LifeStatus[df$Name == df$EngagedWith[k]] <- "Unconscious"
                        df$RoundKilled[df$Name == df$EngagedWith[k]] <- Round
                        df$EnemiesKilled[df$Name == df$Name[k]] <- df$EnemiesKilled[df$Name == df$Name[k]] + 1
                        Action <- paste0("After taking a critical hit, ", df$EngagedWith[k], " (", df$Group[df$Name == df$EngagedWith[k]], ")", " has fallen!")
                        if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                          Summary <- c(Summary, Action)
                        }
                      }
                    }
                  }
                  # ... and if their attack roll is somewhere in the middle...
                  if (ATK > 1 & ATK < 20){
                    # ... add their attack modifier
                    ATK <- ATK + df$ATK[k]
                    # ... if the attack roll is greater than their target's AC, roll damage.
                    if (ATK > df$AC[df$Name == df$EngagedWith[k]]){
                      DMG <- roll_dice(df$DMG[k])
                      df$HP[df$Name == df$EngagedWith[k]] <- df$HP[df$Name == df$EngagedWith[k]] - DMG
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k]," and done ", DMG, " points of damage.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                      # ... and if their target's HP drops below 0 as a result, they will be knocked unconscious. 
                      if (df$HP[df$Name == df$EngagedWith[k]] <= 0){
                        df$HP[df$Name == df$EngagedWith[k]] <- 0
                        df$LifeStatus[df$Name == df$EngagedWith[k]] <- "Unconscious"
                        df$RoundKilled[df$Name == df$EngagedWith[k]] <- Round
                        df$EnemiesKilled[df$Name == df$Name[k]] <- df$EnemiesKilled[df$Name == df$Name[k]] + 1
                        Action <- paste0(df$EngagedWith[k], " (", df$Group[df$Name == df$EngagedWith[k]], ")", " has gone down!")
                        if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                          Summary <- c(Summary, Action)
                        }
                      }
                    }
                    # ... if the attack roll is less than or equal to their target's AC, the attack misses.
                    if (ATK < df$AC[df$Name == df$EngagedWith[k]]){
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but missed.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                    }
                    if (ATK == df$AC[df$Name == df$EngagedWith[k]]){
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but ", df$EngagedWith[k], " just barely escaped without damage.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                    }              
                  }
                }
              }
            }
            # ... and check whether they are currently unconscious.
            if (df$LifeStatus[k] == "Unconscious"){
              # If so, roll a death save...
              DeathSave <- roll_dice("1d20")
              # If the roll a 1, take two failures
              if (DeathSave == 1){
                df_deathsaves$Failed[k] <- df_deathsaves$Failed[k] + 2
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved dramatically closer to death.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll a 20, take two successes
              if (DeathSave == 20){
                df_deathsaves$Saved[k] <- df_deathsaves$Saved[k] + 2
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved dramatically closer to life.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll less than an 11, take one failure
              if (DeathSave > 1 & DeathSave < 11){
                df_deathsaves$Failed[k] <- df_deathsaves$Failed[k] + 1
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved one step closer to death.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll greater than a 10, take one success.
              if (DeathSave > 10 & DeathSave < 20){
                df_deathsaves$Saved[k] <- df_deathsaves$Saved[k] + 1
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved one step closer to life.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              if (df_deathsaves$Saved[k] >= 3){
                df_deathsaves$Saved[k] <- 0
                df_deathsaves$Failed[k] <- 0
                df$LifeStatus[k] <- "Stable"
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has stabilized and avoided death.")
                if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                  Summary <- c(Summary, Action)                    
                }
              }
              if (df_deathsaves$Failed[k] >= 3){
                df_deathsaves$Saved[k] <- 0
                df_deathsaves$Failed[k] <- 0
                df$LifeStatus[k] <- "Dead"
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has succumbed to their injuries and died.")
                if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # Check whether any groups have lost all of their members so far and change the tracker if so
              for (z in 1:length(Groups)){
                if (sum(df$LifeStatus != "Alive" & df$Group == Groups[z]) == nPeople[z])
                  GroupAlive[z] <- FALSE
              }
            }
          }
        }
      }
    }
    # Removing the NA value we needed to start the Summary variable
    Summary <- Summary[-1]
    # Displaying the Play By Play if it was requested
    if (PlayByPlay != "Off"){
      print(Summary)
    }
    # Displaying the final summary of the battle.
    Conclusion <- paste("The battle has ended!", Round, "rounds have passed!", sep = " ")
    for (i in 1:length(Groups)){
      if (GroupAlive[i] == FALSE){
        Conclusion <- paste(Conclusion, paste("All members of", Groups[i], "have fallen.", sep= " "), sep = " ")
      }
      if (GroupAlive[i] == TRUE){  
        Conclusion <- paste(Conclusion, paste(sum(df$LifeStatus == "Alive" & df$Group == Groups[i]), "members of", Groups[i], "remain!", sep= " "))
      }
    }
  }
  # Timed Simulation ----
  if (Ending == "Timed"){
    # Create a life tracker for each group, which takes the form of an array of length Groups.
    # When all members of a group are subdued, their respective tracker will change to value FALSE
    GroupAlive <- NA
    GroupAlive[1:length(Groups)] <- TRUE 
    # During each round of battle (however many it may take)...
    for (i in 1:nRounds){
      # ... For each initiative position ....
      for (j in sort(unique(df$InitiativeOrder))){
        # ... For each battle participant ....
        for (k in rows){
          # Check whether any groups have lost all of their members so far and change the tracker if so
          for (z in 1:length(Groups)){
            if (sum(df$LifeStatus != "Alive" & df$Group == Groups[z]) == nPeople[z])
              GroupAlive[z] <- FALSE
          }
          # ... skip over participants that don't have priority initiative.
          if (df$InitiativeOrder[k] == j){
            # ... and check whether they are currently alive. 
            if (df$LifeStatus[k] == "Alive"){
              # Check whether any groups have lost all of their members so far and change the tracker if so
              for (z in 1:length(Groups)){
                if (sum(df$LifeStatus != "Alive" & df$Group == Groups[z]) == nPeople[z])
                  GroupAlive[z] <- FALSE
              }
              # if there opposing party is dead, cease this turn.
              if (length(grep(TRUE, GroupAlive)) == 1){
                break}
              # if there opposing party is alive, continue this turn.
              if (length(grep(TRUE, GroupAlive)) > 1){
                # If someone has not engaged, randomly choose someone to attack.            
                if (is.na(df$EngagedWith[k])){
                  df$EngagedWith[k] <- sample(df$Name[(df$Group != df$Group[k]) & df$LifeStatus == "Alive"], 1)
                  Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has targeted ", df$EngagedWith[k], ".")
                  if (PlayByPlay == "Everything"){
                    Summary <- c(Summary, Action)
                  }
                }        
                # If the person they were previously engaged with died, randomly choose someone else to attack.            
                if (!is.na(df$EngagedWith[k]) & df$LifeStatus[df$Name == df$EngagedWith[k]] != "Alive"){
                  df$EngagedWith[k] <- sample(df$Name[(df$Group != df$Group[k]) & df$LifeStatus == "Alive"], 1)
                  Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has targeted ", df$EngagedWith[k], ".")
                  if (PlayByPlay == "Everything"){
                    Summary <- c(Summary, Action)
                  }
                }
                # If someone is engaged with someone, let them try to attack..            
                if (!is.na(df$EngagedWith[k]) & df$LifeStatus[df$Name == df$EngagedWith[k]] == "Alive"){
                  ATK <- roll_dice("1d20")
                  # ... if they roll a Natural 1, they'll inflict damage on themselves
                  if (ATK == 1){
                    DMG <- roll_dice(df$DMG[k])
                    df$HP[df$Name == df$Name[k]] <- df$HP[df$Name == df$Name[k]] - DMG
                    Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but hurt themselves in the process and took ", DMG, " points of damage.")
                    if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                      Summary <- c(Summary, Action)
                    }
                    # ... and if their HP drops below 0 as a result, they will be knocked unconscious.                
                    if (df$HP[df$Name == df$Name[k]] <= 0){
                      df$HP[df$Name == df$Name[k]] <- 0
                      df$LifeStatus[df$Name == df$Name[k]] <- "Unconscious"
                      df$RoundKilled[df$Name == df$Name[k]] <-i
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has accidentally committed suicide!")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                        Summary <- c(Summary, Action)
                      }
                    }
                  }
                  # ... if they roll a Natural 20,
                  if (ATK == 20){
                    ATK <- roll_dice("1d20")
                    # ... they get the chance to roll twice more
                    if (ATK == 20){
                      ATK <- roll_dice("1d20")
                      # ,,, and if they successfully roll two more 20s
                      if (ATK == 20){
                        # They will kill their opponent in a single swing.
                        df$HP[df$Name == df$EngagedWith[k]] <- 0
                        df$EnemiesKilled[df$Name == df$Name[k]] <- df$EnemiesKilled[df$Name == df$Name[k]] + 1
                        Action <- paste0("In an unparalleled display of brutality and carnage, ", df$Name[k], " (", df$Group[k], ")", " has annihilated ", df$EngagedWith[k]," with a single attack.")
                        if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                          Summary <- c(Summary, Action)
                        }
                      }
                    }
                    # ... if they do not roll another 20, though, they will still do double damage.
                    if (ATK != 20){
                      DMG <- (roll_dice(df$DMG[k]) * 2)
                      df$HP[df$Name == df$EngagedWith[k]] <- df$HP[df$Name == df$EngagedWith[k]] - DMG
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k]," and done critical damage, at ", DMG, " points total.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                      # ... and if their target's HP drops below 0 as a result, they will be knocked unconscious.  
                      if (df$HP[df$Name == df$EngagedWith[k]] <= 0){
                        df$HP[df$Name == df$EngagedWith[k]] <- 0
                        df$LifeStatus[df$Name == df$EngagedWith[k]] <- "Unconscious"
                        df$RoundKilled[df$Name == df$EngagedWith[k]] <- i
                        df$EnemiesKilled[df$Name == df$Name[k]] <- df$EnemiesKilled[df$Name == df$Name[k]] + 1
                        Action <- paste0("After taking a critical hit, ", df$EngagedWith[k], " (", df$Group[df$Name == df$EngagedWith[k]], ")", " has fallen!")
                        if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                          Summary <- c(Summary, Action)
                        }
                      }
                    }
                  }
                  # ... and if their attack roll is somewhere in the middle...
                  if (ATK > 1 & ATK < 20){
                    # ... add their attack modifier
                    ATK <- ATK + df$ATK[k]
                    # ... if the attack roll is greater than their target's AC, roll damage.
                    if (ATK > df$AC[df$Name == df$EngagedWith[k]]){
                      DMG <- roll_dice(df$DMG[k])
                      df$HP[df$Name == df$EngagedWith[k]] <- df$HP[df$Name == df$EngagedWith[k]] - DMG
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k]," and done ", DMG, " points of damage.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                      # ... and if their target's HP drops below 0 as a result, they will be knocked unconscious. 
                      if (df$HP[df$Name == df$EngagedWith[k]] <= 0){
                        df$HP[df$Name == df$EngagedWith[k]] <- 0
                        df$LifeStatus[df$Name == df$EngagedWith[k]] <- "Unconscious"
                        df$RoundKilled[df$Name == df$EngagedWith[k]] <-i
                        df$EnemiesKilled[df$Name == df$Name[k]] <- df$EnemiesKilled[df$Name == df$Name[k]] + 1
                        Action <- paste0(df$EngagedWith[k], " (", df$Group[df$Name == df$EngagedWith[k]], ")", " has gone down!")
                        if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                          Summary <- c(Summary, Action)
                        }
                      }
                    }
                    # ... if the attack roll is less than or equal to their target's AC, the attack misses.
                    if (ATK < df$AC[df$Name == df$EngagedWith[k]]){
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but missed.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                    }
                    if (ATK == df$AC[df$Name == df$EngagedWith[k]]){
                      Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has attacked ", df$EngagedWith[k],", but ", df$EngagedWith[k], " just barely escaped without damage.")
                      if (PlayByPlay == "Everything" | PlayByPlay == "Attacks"){
                        Summary <- c(Summary, Action)
                      }
                    }              
                  }
                }
              }
            }
            # ... and check whether they are currently unconscious.
            if (df$LifeStatus[k] == "Unconscious"){
              # If so, roll a death save...
              DeathSave <- roll_dice("1d20")
              # If the roll a 1, take two failures
              if (DeathSave == 1){
                df_deathsaves$Failed[k] <- df_deathsaves$Failed[k] + 2
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved dramatically closer to death.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll a 20, take two successes
              if (DeathSave == 20){
                df_deathsaves$Saved[k] <- df_deathsaves$Saved[k] + 2
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved dramatically closer to life.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll less than an 11, take one failure
              if (DeathSave > 1 & DeathSave < 11){
                df_deathsaves$Failed[k] <- df_deathsaves$Failed[k] + 1
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved one step closer to death.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              # If the roll greater than a 10, take one success.
              if (DeathSave > 10 & DeathSave < 20){
                df_deathsaves$Saved[k] <- df_deathsaves$Saved[k] + 1
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has moved one step closer to life.")
                if (PlayByPlay == "Everything"){
                  Summary <- c(Summary, Action)                    
                }
              }
              if (df_deathsaves$Saved[k] >= 3){
                df_deathsaves$Saved[k] <- 0
                df_deathsaves$Failed[k] <- 0
                df$LifeStatus[k] <- "Stable"
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has stabilized and avoided death.")
                if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                  Summary <- c(Summary, Action)                    
                }
              }
              if (df_deathsaves$Failed[k] >= 3){
                df_deathsaves$Saved[k] <- 0
                df_deathsaves$Failed[k] <- 0
                df$LifeStatus[k] <- "Dead"
                Action <- paste0(df$Name[k], " (", df$Group[k], ")", " has succumbed to their injuries and died.")
                if (PlayByPlay == "Everything" | PlayByPlay == "Attacks" | PlayByPlay == "Kills"){
                  Summary <- c(Summary, Action)                    
                }
              }
            
              # Check whether any groups have lost all of their members so far and change the tracker if so
              for (z in 1:length(Groups)){
                if (sum(df$LifeStatus != "Alive" & df$Group == Groups[z]) == nPeople[z])
                  GroupAlive[z] <- FALSE
              }
            }
          }
        }
      }
    }
    
  # Cleaning output ----  
    # Removing the NA value we needed to start the Summary variable
    Summary <- Summary[-1]
    # Displaying the final summary of the battle.
    Conclusion <- paste(nRounds, "rounds have passed!", sep = " ")
    for (i in 1:length(Groups)){
      if (GroupAlive[i] == FALSE){
        Conclusion <- paste(Conclusion, paste("All members of", Groups[i], "have fallen.", sep= " "), sep = " ")
      }
      if (GroupAlive[i] == TRUE){  
        Conclusion <- paste(Conclusion, paste(sum(df$LifeStatus == "Alive" & df$Group == Groups[i]), "members of", Groups[i], "remain!", sep= " "))
      }
    }
  }
  # Cleaning Summary output
  Conclusion
  Summary <- c(Summary, Conclusion)
  Summary <- as.data.frame(Summary)
  colnames(Summary[1]) <- "Summary"
  # If we want data fighrer stats
  if (Output == "Table"){
    # Returning the final summary dataframe. 
    return(df)
  }
  # If we want a battle summary
  if (Output == "Text"){
    # Returning the final summary dataframe. 
    return(Summary)
  }
}